### ISSUE TITLE
BUG: Static content is not correctly served when using configurable base url

### ISSUE THREAD

**Issue by majikman111** [PrefectHQ/ui#861]
**Bug Description**
When using a configurable base URL (as implemented in #849 ) the root index.html is correctly served from the configured base path, but follow on requests (both from built content and links inserted during build or hardcoded into index.html) ignore the base url and make requests directly from the root path ("/"). 

**Steps To Reproduce**
1. Deploy a prefect server to docker with PREFECT_SERVER__BASE_URL configured. This was achieved by modifying the docker-compose.yml packaged with Prefect and running `prefect server start --ui-version 2021-05-25`.
2. Browse to the configured ui and base url.
3. Open the browser debug console and observe that the initial request is correctly proxied, but additional requests ignore the base url. 

**Browsers Tested:**
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [x] Edge
* [ ] IE

----------
**Notes**
When using a standard Nginx reverse proxy ALL requests must be routed through the configured base URL, otherwise the proxy cannot route the requests to the appropriate backend app.

I can't build to test this, but likely setting the routers to default to "./" as a base rather than "/" should fix this issue at least at the root level of index.html. The UI nginx config will likely also need to be updated to dynamically use the base url variable.

**Comment by znicholasbrown** [comment]
Hi @majikman111 - with the setup you're testing, can you post the values from `settings.json`? (feel free to redact any sensitive URLs)

**Comment by majikman111** [comment]
settings.json
{
  "server_url": "http://localhost:4200/graphql",
  "base_url": "/prefectui/"
}

Updated snippet from docker-compose.yml
  ui:
    image: "prefecthq/ui:${PREFECT_UI_TAG:-latest}"
    ports:
      - "${UI_HOST_PORT:-8080}:8080"
    command: "/intercept.sh"
    environment:
      PREFECT_SERVER__APOLLO_URL: ${APOLLO_URL:-http://localhost:4200/graphql}
      PREFECT_SERVER__BASE_URL: "/prefectui/"

**Comment by znicholasbrown** [comment]
Perfect thank you - let me investigate

**Comment by majikman111** [comment]
@znicholasbrown Any updates on this issue?

**Comment by znicholasbrown** [comment]
Unfortunately I haven't had a chance to look at it yet since we're at the end of the quarter. I should have a little more time in the next couple of weeks.

**Comment by trevorcampbell** [comment]
Just adding a note that I can reproduce this bug on `0.15.5` (and a +1 to the request to address it!). I used
```
prefect server config > docker-compose.yml
```
to dump the compose yaml, edited the file to include the `PREFECT_SERVER__BASE_URL`,
```
services:
    ...
    ui:
        ....
        environment:
                  PREFECT_SERVER__APOLLO_URL: http://localhost:4200/graphql
                  PREFECT_SERVER__BASE_URL: /prefect/
````
set up the reverse proxy, and run the server using
```
docker-compose up
```
The first request gets proxied properly, and subsequent requests ignore the base_url.

**Comment by massintha-riaktr** [comment]
Hi there,

Would it be possible to have a recipe on how to build an image of the prefect UI with a hardcoded base URL? As long as the UI works behind a reverse proxy it doesn't need to be configurable at runtime...at least for my use case.

**Comment by majikman111** [comment]
@massintha-riaktr  I had to make modifications to the app and build my own docker container, essentially the changes in this PR with the base path set to prefectui PrefectHQ/ui#450.
I've published the image here https://hub.docker.com/repository/docker/majikman111/prefect-ui-proxy
The last build is a little out of date but should work for core builds.

**Comment by amitza** [comment]
This still happens in in current UI version:
`docker.io/prefecthq/ui@sha256:bdd84f14765e6fa64a45e999fae2d51884e352df0ba65b04389dc38d646474f1`
